services:
  python-ocr:
    container_name: rp-python-ocr-app
    platform: linux/amd64
    build: .
    ports:
      - "6007:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ROOT_PATH=${ROOT_PATH:-}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
